/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["getUsers"];
        put?: never;
        /** Create a new user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Geo: {
            lat?: string;
            lng?: string;
        };
        Address: {
            street?: string;
            suite?: string;
            city?: string;
            zipcode?: string;
            geo?: components["schemas"]["Geo"];
        };
        Company: {
            name?: string;
            catchPhrase?: string;
            bs?: string;
        };
        User: {
            id: number;
            name: string;
            username: string;
            email: string;
            address?: components["schemas"]["Address"];
            phone?: string;
            website?: string;
            company?: components["schemas"]["Company"];
        };
        NewUser: {
            name: string;
            username: string;
            email: string;
            phone?: string;
            website?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUser"];
            };
        };
        responses: {
            /** @description User created (mocked by JSONPlaceholder) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
